- GitTrends.Mobile.Shared/Constants/PageTitles.cs
- GitTrends.Shared/GitTrends.Shared.projitems
- GitTrends.Shared/Models/ReferringSiteModel.cs
- GitTrends.UITests/AppInitializer.cs
- GitTrends.UITests/GitTrends.UITests.csproj
- GitTrends.UITests/Pages/BasePage.cs
- GitTrends.UITests/Pages/ReferringSitesPage.cs
- GitTrends.UITests/Pages/RepositoryPage.cs
- GitTrends.UITests/Pages/SettingsPage.cs
- GitTrends.UITests/Pages/TrendsPage.cs
- GitTrends.UITests/Tests/BaseTest.cs
- GitTrends.UITests/Tests/LaunchTests.cs
- GitTrends.iOS/AppDelegate.cs
- GitTrends.sln
- GitTrends/Models/MobileReferringSiteModel.cs
- GitTrends/Pages/ReferringSitesPage.cs
- GitTrends/Services/GitHubApiV3Service.cs
- GitTrends/ViewModels/ReferringSitesViewModel.cs
- GitTrends/Views/ReferringSites/ReferringSitesDataTemplateSelector.cs
- Adds UI Testing Framework
- Implements IAsyncEnumerable for `GitHubApiV3Service.GetReferingSites`
> Add UI Test Framework

- GitTrends.iOS/GitTrends.iOS.csproj
https://devblogs.microsoft.com/xamarin/uiwebview-deprecation-xamarin-forms/
> Enable monotouch arg for UIWebView

- GitTrends/App.cs
- GitTrends/Pages/RepositoryPage.cs
- GitTrends/Services/XamarinFormsService.cs
- GitTrends/Views/ReferringSites/ReferringSitesDataTemplateSelector.cs
- GitTrends/Views/Repository/RepositoryDataTemplateSelector.cs
- Add Extension Method SetSelectedStateBackgroundColor which can be used to specify a specific background color when the item is selected
> Remove Selected Item Background Color

- GitTrends.Shared/Constants/SortingConstants.cs
- GitTrends.UITests/Tests/RepositoriesTests.cs
- GitTrends/Pages/RepositoryPage.cs
- GitTrends/Services/NotificationService.cs
- GitTrends/Services/SortingService.cs
- GitTrends/Themes/LightTheme.cs
- GitTrends/Views/Repository/RepositoryDataTemplateSelector.cs
Adds 3 Repository DataTemplates:
- ClonesDataTemplate
- ViewsDataTemplate
- IssuesForksDataTemplate
> Implement 3 Sorting Categories

- GitTrends.Mobile.Common/Constants/PullToRefreshFailedConstants.nl.resx
- GitTrends.Mobile.Common/Constants/ReferringSitesPageConstants.nl.resx
As requested; added the (now) missing NL translations
> Add updated NL translations

- GitTrends.Android/GarbageCollector.config
- GitTrends.Android/GitTrends.Android.csproj
- GitTrends/Views/Repository/BaseRepositoryDataTemplate.cs
- GitTrends/Views/Repository/RepositoryDataTemplateSelector.cs
- GitTrends/Views/Repository/StatisticsLabel.cs
- Remove RepositoryDataTemplate Bindings
- Increase Nursery Size
> Improve Android CollectionView Scrolling

- GitTrends.Mobile.Common/GitTrends.Mobile.Common.csproj
- GitTrends.Mobile.Common/Services/MobileSortingService.cs
- GitTrends.iOS/CustomRenderers/IndicatorViewCustomRenderer.cs
- GitTrends/Pages/RepositoryPage.cs
- GitTrends/Services/ContainerService.cs
- GitTrends/ViewModels/RepositoryViewModel.cs
- GitTrends/Views/Base/ExtendedSwipeView.cs
- GitTrends/Views/Repository/BaseRepositoryDataTemplate.cs
- GitTrends/Views/Repository/RepositoryDataTemplateSelector.cs
Closes https://github.com/brminnick/GitTrends/issues/35
> Add Swipe-to-Favorite

- GitTrends.iOS/CustomRenderers/SearchPageRenderer.cs
- GitTrends/Pages/RepositoryPage.cs
Fixes SearchPageRenderer to accommodate the UISearchController height
Closes #171
> Fix iOS Search Page Height

- GitTrends.Mobile.Common/Constants/AboutPageConstants.nl.resx
- GitTrends.Mobile.Common/Constants/EmptyDataViewConstantsInternal.nl.resx
- GitTrends.Mobile.Common/Constants/ThemeConstants.nl.resx
- GitTrends.Mobile.Common/Constants/TrendsChartTitleConstants.nl.resx
- GitTrends.Mobile.Common/GitTrends.Mobile.Common.csproj
Fixes #182 
- Adds missing files
- Adds missing translations
> Add missing NL translations

- GitTrends.Mobile.Common/Constants/AboutPageConstants.bs.resx
- GitTrends.Mobile.Common/Constants/EmptyDataViewConstantsInternal.bs.resx
- GitTrends.Mobile.Common/Constants/ThemeConstants.bs.resx
- GitTrends.Mobile.Common/Constants/TrendsChartTitleConstants.bs.resx
- GitTrends.Mobile.Common/GitTrends.Mobile.Common.csproj
This should implement all the stuff mentioned in the [issue](https://github.com/brminnick/GitTrends/issues/178).
> Added additional Bosnian translations

- GitTrends.Mobile.Common/Constants/AboutPageConstants.Designer.cs
- GitTrends.Mobile.Common/Constants/AboutPageConstants.en.resx
- GitTrends.Mobile.Common/Constants/AboutPageConstants.es.resx
- GitTrends.Mobile.Common/Constants/AboutPageConstants.resx
- GitTrends.Mobile.Common/Constants/RepositoryPageConstants.es.resx
- GitTrends/Pages/AboutPage.cs
Add Spanish Translation for:
- GitHub and Request Feature Buttons in About Us Page
> Add Spanish Translation for GitHub and Request Feature Buttons in About Us Page

- GitTrends.Mobile.Common/Constants/AboutPageConstants.nl.resx
- GitTrends.Mobile.Common/Constants/RepositoryPageConstants.nl.resx
> Added missing NL translations

- GitTrends.Mobile.Common/Constants/AboutPageConstants.bs.resx
- GitTrends.Mobile.Common/Constants/RepositoryPageConstants.bs.resx
> Added missing Bosnian translations

- GitTrends.Android/GitTrends.Android.csproj
- GitTrends.Functions/GitTrends.Functions.csproj
- GitTrends.Mobile.Common/GitTrends.Mobile.Common.csproj
- GitTrends.UITests/GitTrends.UITests.csproj
- GitTrends.UnitTests/GitTrends.UnitTests.csproj
- GitTrends.iOS/GitTrends.iOS.csproj
- GitTrends/GitTrends.csproj
This PR ensures that the CI Build Tools catch all Null warnings
https://stackoverflow.com/a/62116924/5953643
> Add <WarningsAsErrors>nullable</WarningsAsErrors>

- GitTrends.Mobile.Common/Constants/AboutPageConstants.de.resx
- GitTrends.Mobile.Common/Constants/RepositoryPageConstants.de.resx
> Added new German translations

- GitTrends.Mobile.Common/Constants/AboutPageConstants.cs.resx
- GitTrends.Mobile.Common/Constants/AppStoreRatingRequestConstants.cs.resx
- GitTrends.Mobile.Common/Constants/CultureConstants.cs
- GitTrends.Mobile.Common/Constants/DemoUserConstants.cs.resx
- GitTrends.Mobile.Common/Constants/EmptyDataViewConstantsInternal.cs.resx
- GitTrends.Mobile.Common/Constants/GitHubLoginButtonConstants.cs.resx
- GitTrends.Mobile.Common/Constants/NotificationConstants.cs.resx
- GitTrends.Mobile.Common/Constants/OnboardingConstants.cs.resx
- GitTrends.Mobile.Common/Constants/PageTitles.cs.resx
- GitTrends.Mobile.Common/Constants/PageTitles.en.resx
- GitTrends.Mobile.Common/Constants/PullToRefreshFailedConstants.cs.resx
- GitTrends.Mobile.Common/Constants/ReferringSitesPageConstants.cs.resx
- GitTrends.Mobile.Common/Constants/RepositoryPageConstants.cs.resx
- GitTrends.Mobile.Common/Constants/ReviewServiceConstants.cs.resx
- GitTrends.Mobile.Common/Constants/SettingsPageConstants.cs.resx
- GitTrends.Mobile.Common/Constants/SortingConstants.cs.resx
- GitTrends.Mobile.Common/Constants/SplashScreenPageConstants.cs.resx
- GitTrends.Mobile.Common/Constants/ThemeConstants.cs.resx
- GitTrends.Mobile.Common/Constants/TrendsChartTitleConstants.cs.resx
- GitTrends.Mobile.Common/Constants/WelcomePageConstants.cs.resx
- GitTrends.Mobile.Common/GitTrends.Mobile.Common.csproj
- GitTrends.iOS/Info.plist
Working on a translation in the Czech language, because this app is awesome!
> Czech translation

- GitTrends.Mobile.Common/Constants/ManageOrganizationsConstants.cs.resx
- GitTrends.Mobile.Common/Constants/PullToRefreshFailedConstants.cs.resx
- GitTrends.Mobile.Common/Constants/SettingsPageConstants.cs.resx
Fixes https://github.com/brminnick/GitTrends/issues/346
> Update Czech translations

- GitTrends.Mobile.Common/Constants/ManageOrganizationsConstants.de.resx
- GitTrends.Mobile.Common/Constants/PullToRefreshFailedConstants.de.resx
- GitTrends.Mobile.Common/Constants/SettingsPageConstants.de.resx
> Added translations of new keys for German

- GitTrends.Mobile.Common/Constants/ManageOrganizationsConstants.ru.resx
- GitTrends.Mobile.Common/Constants/PullToRefreshFailedConstants.ru.resx
- GitTrends.Mobile.Common/Constants/SettingsPageConstants.ru.resx
Courtesy of @Veroni4ka
Fixes #352
> Add Russian Translations for v2.3.0

- GitTrends.Mobile.Common/Constants/ManageOrganizationsConstants.es.resx
- GitTrends.Mobile.Common/Constants/PullToRefreshFailedConstants.es.resx
- GitTrends.Mobile.Common/Constants/SettingsPageConstants.es.resx
Courtesy of  @Pujolsluis
Fixes #344
> Add Spanish Translations for v2.3.0

- GitTrends.Mobile.Common/Constants/ManageOrganizationsConstants.tr.resx
- GitTrends.Mobile.Common/Constants/PullToRefreshFailedConstants.tr.resx
- GitTrends.Mobile.Common/Constants/SettingsPageConstants.tr.resx
> Add Turkish Translations for v2.3.0

- GitTrends.Mobile.Common/Constants/ManageOrganizationsConstants.nl.resx
- GitTrends.Mobile.Common/Constants/PullToRefreshFailedConstants.nl.resx
- GitTrends.Mobile.Common/Constants/SettingsPageConstants.nl.resx
As requested!
Before merging also see #364
> Add missing NL translations for new version

- GitTrends.Mobile.Common/Constants/ManageOrganizationsConstants.bs.resx
- GitTrends.Mobile.Common/Constants/PullToRefreshFailedConstants.bs.resx
- GitTrends.Mobile.Common/Constants/SettingsPageConstants.bs.resx
- GitTrends.Mobile.Common/GitTrends.Mobile.Common.csproj
> Updated Bosnian translations

- GitTrends.Android/Properties/AndroidManifest.xml
- GitTrends.Shared/Constants/GithubConstants.cs
- GitTrends.Shared/Models/Repository.cs
- GitTrends.iOS/Info.plist
- GitTrends/Pages/AboutPage.cs
- GitTrends/Resources/Fonts/FontAwesomeConstants.cs
- GitTrends/Services/GitHubApiV3Service.cs
- GitTrends/ViewModels/RepositoryViewModel.cs
- GitTrends/ViewModels/SettingsViewModel.cs
- GitTrends/Views/Repository/BaseRepositoryDataTemplate.cs
This PR adds a button to navigate to the repository's GitHub page.
If the user has the GitHub App installed, the External Link Button will launch the GitHub App.
| Button | Result |
| --| -- |
| ![Simulator Screen Shot - iPhone 13 Pro - 2022-04-14 at 15 42 06](https://user-images.githubusercontent.com/13558917/163489471-9c52fb17-10c3-4899-a3c9-aba2efffe540.png) | ![Simulator Screen Shot - iPhone 13 Pro - 2022-04-14 at 15 42 13](https://user-images.githubusercontent.com/13558917/163489468-a5b10ec8-b15f-40e2-ad0c-e5a1d7bd4d8c.png) |
> Add External Link Button

- GitTrends.Android/GitTrends.Android.csproj
- GitTrends.Android/Properties/AndroidManifest.xml
- GitTrends.Functions/GitTrends.Functions.csproj
- GitTrends.Functions/global.json
- GitTrends.Shared/Constants/AzureConstants.cs
- GitTrends.UITests/Models/Repository.cs
- GitTrends.UnitTests/MockServices/ExtendedBackgroundFetchService.cs
- GitTrends.UnitTests/ServiceCollection.cs
- GitTrends.UnitTests/Tests/Base/BaseTest.cs
- GitTrends.UnitTests/Tests/Services/FavIconServiceTests.cs
- GitTrends.UnitTests/Tests/Services/MobileSortingServiceTests.cs
- GitTrends.UnitTests/Tests/ViewModels/RepositoryViewModel/RepositoryViewModelTests_AbuseApiLimit_GraphQLApi.cs
- GitTrends.UnitTests/Tests/ViewModels/RepositoryViewModel/RepositoryViewModelTests_AbuseApiLimit_RestApi.cs
- GitTrends.UnitTests/Tests/ViewModels/RepositoryViewModel/RepositoryViewModelTests_MaximumApiCallLimit_GraphQLApi.cs
- GitTrends.UnitTests/Tests/ViewModels/RepositoryViewModel/RepositoryViewModelTests_MaximumApiCallLimit_RestApi.cs
- GitTrends.iOS/GitTrends.iOS.csproj
- GitTrends.iOS/Info.plist
- GitTrends/GitTrends.csproj
- GitTrends/Services/BackgroundFetchService.cs
- azure-pipelines.yml
> Update Azure Functions

- GitTrends.UnitTests/Tests/ViewModels/RepositoryViewModel/Base/RepositoryViewModelTests_MaximumApiCallLimit.cs
- GitTrends/Pages/RepositoryPage.cs
- GitTrends/Views/Base/ExtendedSwipeView.cs
- GitTrends/Views/Repository/BaseRepositoryDataTemplate.cs
- Remove `ExtendedSwipeView.Tapped`
- Leverage `ExtendedSwipeView.Command`
- Remove unused code
> Refactor `ExtendedSwipeView`
